name: terminalworm
version: git
summary: A remake of the classic Snake game
description: |
  A remake of the classic Snake game in your terminal
grade: stable
confinement: strict

apps:
  terminalworm:
    command: python3 $SNAP/main.py
     
parts: 
  terminalworm:
    source: https://github.com/kz6fittycent/Terminal_Worm
    source-type: git
    plugin: python
    python-version: python3
    
    build-packages:
      - python3
      
    stage-packages:
      - python3

  publish:
    plugin: copy
    files:
      ./main.py: main.py
